name: Backend CD
on:
  push:
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 147.45.139.11
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/cookieless/backend
            git pull origin main
            docker-compose down
            docker-compose up -d --build